#Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.worldofsoccer: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

#for h2
spring:
  config:
    activate:
      on-profile: h2

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:teams-db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR,VALUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none   #use create to allow jpa to auto-generate from Entity classes; use none to use schema-h2.sql

    defer-datasource-initialization: true

  sql:
    init:
      platform: h2
      mode: always


---
#for docker
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres1/teams-db
    username: user
    password: pwd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          auto-quote-keyword: true
    defer-datasource-initialization: true
  sql:
    init:
      platform: psql
      mode: always
      schema-locations: "classpath:/schema-psql.sql"
server:
  port: 8080